server:
  port: 8081

spring:
  application:
    name: payment-service

grpc:
  client:
    account-service:
      address: 'static://localhost:50051'
      negotiationType: plaintext

logging:
  level:
    com.example.payment: INFO

# Swagger / OpenAPI UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
